apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::294990666552:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::294990666552:role/UdacityFlaskDeployCBKubectlRole
      username: build

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-06T08:24:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-06T08:24:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-02-06T09:01:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8198"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3a36c286-0c69-42b0-886d-bdf0e5f6497b
